config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products

  get    "products_mine/", to: "products#show_equipaments", as: :products_user
  get    "products_rented", to: "products#show_rentals_equipaments", as: :renteds_user

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get    "products/:product_id/rentals/new",    to: "rentals#new",  as: :new_product_rental
  post   "products/:product_id/rentals/",       to: "rentals#create", as: :product_rentals
  get    "rentals/:id",                         to: "rentals#show", as: :rental
  get    "rentals/:id/edit/",                   to: "rentals#edit", as: :review
  patch  "rentals/:id/",                        to: "rentals#update"
  get    "rentals_list/",                       to: "rentals#index", as: :rental_list 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_description,
    against: [ :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :begin_date, presence: true
  validates :end_date, presence: true
  validates :rental_price, presence: true
  validates :product, presence: true
  validates :user, presence: true

  validates :rental_price, numericality: { greater_than: 0 }
  validate :end_date_must_be_greater_than_begin_date

  def end_date_must_be_greater_than_begin_date
    if (begin_date > end_date) || (begin_date < Date.today)
      errors.add(:begin_date, ": O início não pode ser no passado e nem após a data de término")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :rentals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

     if params[:query].present?
      @products = Product.search_by_description(params[:query])
    else
      @products = Product.all
    end

    # the `geocoded` scope filters only products with coordinates (latitude & longitude)
    @markers = @products.geocoded.map do |prod|
      {
        lat: prod.latitude,
        lng: prod.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { prod: prod })
      }

    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.price = product_params[:price].to_f * 100
    @product.user = current_user

    if @product.save
      redirect_to @product, notice: 'Equipamento cadastrado.'
    else
      render :new
    end
  end

  def show
    @reviews = {}
    Rental.where(product: @product).each do |x|
      @reviews[x.user_id] = x.costumer_review unless x.costumer_review.nil?
    end
    @marker = {
        lat: @product.latitude,
        lng: @product.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { prod: @product })
      }
  end

  def show_equipaments
    @products = Product.where(user_id: current_user)
  end

  def show_rentals_equipaments
    @products = []
      Rental.where(user_id: current_user).each do |rental|
      @products << rental.product
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      @product.price = product_params[:price].to_f * 100
      @product.save
      redirect_to @product, notice: 'As informações foram corretamentes editadas'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'O equipamento foi removido'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product).permit(:description, :price, :address, :latitude, :longitude, :photo)
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    def new
        @product = Product.find(params[:product_id])
        @rental = Rental.new
    end

    def create
        @rental = Rental.new(rental_params)
        @rental.end_date = Date.parse(@rental.end_date.to_s)
        @rental.begin_date = Date.parse(@rental.begin_date.to_s)
        @product = Product.find(params[:product_id])
        @rental.product = @product
        @rental.rental_price = ( @rental.end_date - @rental.begin_date ).to_i*@product.price
        @rental.user = current_user
        if @rental.save
          redirect_to rental_path(Rental.last.id), notice: 'Aluguel cadastrado.'
        else
          render :new
        end

      end

    def show
      @rental = Rental.find(params[:id])
      @reviews = {}
      Rental.where(user_id: @rental.user_id).each do |x|
        @reviews[x.product.description] = x.renter_review unless x.renter_review.nil?
      end

    end

    def edit
      @rental = Rental.find(params[:id])
    end

    def update
      @rental = Rental.find(params[:id])
      @rental.update(rental_params2)
      redirect_to rental_path(@rental)

    end

    def index
      @rental_user = Rental.where(user_id: current_user)

      rental_products = []
      rental_products = Product.where(user_id: current_user)
      @rental_owner = []
      rental_products.each do |product|
        @rental_owner << Rental.where(product: product)
      end
      @rental_owner = @rental_owner.flatten.map { |rental| rental.id}
      @rental_owner.sort!
      @rental_owner = @rental_owner.map { |id| Rental.find(id) }


    end


      private

      def rental_params
        params.require(:rental).permit(:begin_date, :end_date)
      end

      def rental_params2
        params.require(:rental).permit(:costumer_review, :renter_review)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsForRent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div id="page-container">
      <div id="content-wrap">
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex col-sm-12" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1541625602330-2277a4c46182?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
  <div class="banner-container">
    <div class="col-md-6 pl-100">
      <h1>Seja <strong>livre</strong> para escolher.</h1>
      <p>Pratique um novo esporte todos os dias. Encontre qualquer equipamento perto de você.</p>
    </div>
  </div>
  <div class="box-search col-sm-5">
    <div>
      <%= form_tag products_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Encontre um equipamento"
      %>
      <p></p>
      <%= submit_tag "Buscar", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>
<div class="flex-container">
  <%= link_to products_path do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1525289792728-f43da278fcd6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80)">Busque seu equipamento</div>
  <% end %>
  <% if @user == current_user %>
  <%= link_to new_user_registration_path do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1569074187119-c87815b476da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=625&q=80)">Abra sua conta</div>
  <% end %>
  <% else %>
  <%= link_to rental_list_path do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1569074187119-c87815b476da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=625&q=80)">Listar Aluguéis</div>
  <% end %>
  <% end %>
  <% if @user == current_user %>
  <%= link_to new_user_session_path do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1495555687398-3f50d6e79e1e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">Alugue seu equipamento</div>
  <% end %>
  <% else %>
  <%= link_to new_product_path do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1495555687398-3f50d6e79e1e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">Alugue seu equipamento</div>
  <% end %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <% @product.price = @product.price.to_f/100 %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description, label: "Produto" %>
    <%= f.input :address, label: "Endereço" %>
    <%= f.input :price, label: "Preço" %>
    <%= f.input :photo, as: :file, label: "Inserir imagem" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Criar novo produto", class: "btn btn-ghost" %>
  </div>
<% end %>

app/views/products/_info_window.html.erb
<h2><%= prod.description %></h2>
<p><%= prod.address %></p>
<h2><%= "R$ #{"%.2f" % (prod.price.to_f/100)}/dia" %></h2>

app/views/products/edit.html.erb
<div class="container justify-content-center col-sm-6">
  <div class="form-container">


    <h1>Alterar dados do equipamento</h1>


    <%= simple_form_for(@product) do |f| %>
    <% @product.price = @product.price.to_f/100 %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :description, label: "Produto" %>
      <%= f.input :address, label: "Endereço" %>
      <%= f.input :price, label: "Preço" %>
      <%= f.input :photo, as: :file, label: "Inserir imagem" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, value: "Atualizar produto", class: "btn btn-ghost" %>
    </div>
  <% end %>
    <%= link_to 'Voltar', product_path, class: "btn btn-ghost" %>
  </div>
</div>

app/views/products/index.html.erb
<div class="products-container">
  <div class="container justify-content-between col-sm-7">

    <div class="box-search">
      <%= form_tag products_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control-search",
        placeholder: "Encontre um equipamento"
      %>
      <%= submit_tag "Buscar", class: "btn btn-info" %>
      <% end %>
    </div>

    <div class="cards">
      <% @products.each do |product| %>
      <%= link_to product_path(product) do %>
      <div class="card-product">
        <% if product.photo.attached? %>

        <%= cl_image_tag product.photo.key, height: 75, width: 100, crop: :fill %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dzml8ygng/image/upload/v1600970816/bicicleta-c255c8fd010a02d89702c6050d626217293e3ed9889eb28e287d16e69917f5d2_ziqhsf.jpg", style: "height:75px; width:100px" %>

        <% end %>
        <div class="card-product-infos">
          <h2><%= product.description %></h2>
          <p>R$ <%= "%.2f" % (product.price.to_f / 100) %> ao dia</p>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>


  </div>
  <div class="container col-sm-5">
    <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container justify-content-center col-sm-6">
  <div class="form-container">

    <h1>Cadastrar novo equipamento</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Voltar', products_path, class: "btn btn-ghost" %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">

  <div class="flex-container">
    <div class="container col-sm-7">
      <div class="box-product">
        <div class="img-product">
          <% if @product.photo.attached? %>
          <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
          <% else %>
          <%= image_tag "https://res.cloudinary.com/dzml8ygng/image/upload/v1600970816/bicicleta-c255c8fd010a02d89702c6050d626217293e3ed9889eb28e287d16e69917f5d2_ziqhsf.jpg", style: "height:300px; width:400px" %>
          <% end %>
        </div>

        <div class="description-container">
          <p>
            <strong>Equipamento:</strong>
            <%= @product.description %>
          </p>
          <p>
            <strong>Onde buscar:</strong>
            <%= @product.address %>
          </p>
          <p>
            <strong>Preço por dia:</strong>
            R$ <%= "%.2f" % (@product.price.to_f/100) %>
          </p>
          <p>
            <strong>Usuário:</strong>
            <%= @product.user.email %>
          </p>
        </div>
        <div>
          <% if @product.user == current_user %>
            <%= link_to 'Editar', edit_product_path(@product), class: "btn btn-ghost" %>
            <%= link_to 'Remover', product_path(@product), method: :delete, class: "btn btn-ghost", data: {confirm: "Você realmente deseja remover o equipamento?"} %>
          <% else %>
            <%= link_to 'Alugue este equipamento', new_product_rental_path(@product), class: "btn btn-ghost" %>
          <% end %>
          <%= link_to 'Voltar', products_path, class: "btn btn-ghost" %>
        </div>
      </div>
      <div class="review-container mt-20">

        <div class="title">Comentários</div>
        <table class="table table-borderless">
          <thead class="thead-dark">
            <% if @reviews.size.positive? %>
              <tr>
                <th scope="col">Usuário</th>
                <th scope="col">Comentário</th>
              </tr>
            </thead>
            <tbody>
              <% @reviews.keys.each do |user| %>
                <tr>
              <td><%= user %></td>
              <td><%= @reviews[user] %></td>
                </tr>
              <% end %>
              <% else %>
                <p class="title">Seja o primeiro a comentar</p>
              <% end %>
            </tbody>

        </table>


      </div>
    </div>
    <div class="container col-sm-5">
      <div class="map" id="mapForOne"
      style="width: 100%; height: 600px;"
      data-markers="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/products/show_equipaments.html.erb
<div class="products-container">
  <div class="container justify-content-between col-sm-7">

    <div class="box-search">
      <%= form_tag products_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control-search",
        placeholder: "Encontre um novo equipamento"
      %>
      <%= submit_tag "Buscar", class: "btn btn-info" %>
      <% end %>
    </div>

    <div class="cards">
      <% @products.each do |product| %>
      <%= link_to product_path(product) do %>
      <div class="card-product">
        <% if product.photo.attached? %>
        <%= cl_image_tag product.photo.key, height: 75, width: 100, crop: :fill %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dzml8ygng/image/upload/v1600970816/bicicleta-c255c8fd010a02d89702c6050d626217293e3ed9889eb28e287d16e69917f5d2_ziqhsf.jpg", style: "height:75px; width:100px" %>
        <% end %>
        <div class="card-product-infos">
          <h2><%= product.description %></h2>
          <p>R$ <%= "%.2f" % (product.price.to_f / 100) %> ao dia </p>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show_rentals_equipaments.html.erb
<div class="products-container">
  <div class="container justify-content-between col-sm-7">

    <div class="box-search">
      <%= form_tag products_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control-search",
        placeholder: "Encontre um equipamento"
      %>
      <%= submit_tag "Buscar", class: "btn btn-info" %>
      <% end %>
    </div>

    <div class="cards">
      <% @products.each do |product| %>
      <%= link_to product_path(product) do %>
      <div class="card-product">
        <% if product.photo.attached? %>
        <%= cl_image_tag product.photo.key, height: 75, width: 100, crop: :fill %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dzml8ygng/image/upload/v1600970816/bicicleta-c255c8fd010a02d89702c6050d626217293e3ed9889eb28e287d16e69917f5d2_ziqhsf.jpg", style: "height:75px; width:100px" %>
        <% end %>
        <div class="card-product-infos">
          <h2><%= product.description %></h2>
          <p>R$ <%= "%.2f" % (product.price.to_f / 100) %> ao dia</p>
          <% if product.user == current_user %>
          <p>Seu equipamento</p>
          <% end %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/edit.html.erb
<div class="container justify-content-center">
  <div class="form-container">

    <% if current_user.id == @rental.product.user_id  %>

    <div class="container justify-content-center col-sm-6">
      <h3>Avaliação do Usuário</h3>
        <%= simple_form_for [ @rental ] do |f| %>
        <%= f.input :renter_review, label: 'Deixe seu comentário' %>
        <%= f.submit "Enviar avaliação", class: "btn btn-ghost" %>
        <% end %>
    </div>

    <% elsif current_user.id == @rental.user_id  %>

    <div class="container justify-content-center col-sm-6">
      <h3>Avaliação do Proprietário</h3>
        <%= simple_form_for [ @rental ] do |f| %>
        <%= f.input :costumer_review, label: 'Deixe seu comentário' %>
        <%= f.submit "Enviar avaliação", class: "btn btn-ghost" %>
        <% end %>
    </div>

    <% else %>

        <p>Não autorizado</p>

    <% end %>
  </div>
</div>

app/views/rentals/index.html.erb
<div class="review-container mt-20">
  <div class="container col-sm-8">

    <table class="table table-borderless">

        <div class="title">Equipamentos alugados por você</div>
        <thead class="thead-dark">
        <% if @rental_owner.size.positive? %>
            <tr>
            <th scope="col">Produto</th>
            <th scope="col">Usuário</th>
            <th scope="col">Período</th>
            <th scope="col">Valor do Aluguel</th>
            <th scope="col">Comentar</th>
            </tr>
        </thead>
        <tbody>
        <% receita_total = 0 %>
            <% @rental_owner.each do |rental| %>
            <tr>
            <td><%= rental.product.description %></td>
            <td><%= rental.user_id %></td>
            <td><%= rental.begin_date %> a <%= rental.end_date %></td>
            <td> R$ <%= "%.2f" % (rental.rental_price.to_f / 100) %></td>
            <% receita_total += rental.rental_price %>
            <td><%= link_to "Link", rental_path(rental.id) %></td>
            </tr>
            <% end %>
            <% else %>
            <p><%= link_to "Disponibilize seu equipamento", new_product_path, class: "btn btn-ghost" %></p>
            <% end %>
        </tbody>

    </table>
    <div class="title">Receita total com aluguéis:
      <p class="sub-title">R$ <%= "%.2f" % (receita_total.to_f/100)  %></p>
    </div>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="container justify-content-center col-sm-4">
  <div class="form-container">
    <%= simple_form_for [ @product, @rental ] do |f| %>
    <%= f.input :begin_date, label: 'Data de início', as: :date, html5: true %>
    <%= f.input :end_date, label: 'Data de termino', as: :date, html5: true %>
    <%= f.submit "Alugar", class: "btn btn-ghost" %>
    <%= link_to 'Voltar', product_path(@product), class: "btn btn-ghost" %>
    <% end %>
  </div>
</div>

app/views/rentals/show.html.erb
<% if current_user.id == @rental.product.user_id || current_user.id == @rental.user_id %>
<div class="container">

  <div class="box-product">
    <div class="img-product">
        <% if @rental.product.photo.attached? %>
        <%= cl_image_tag @rental.product.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dzml8ygng/image/upload/v1600970816/bicicleta-c255c8fd010a02d89702c6050d626217293e3ed9889eb28e287d16e69917f5d2_ziqhsf.jpg", style: "height:300px; width:400px" %>
        <% end %>
    </div>

    <div class="description-container">
      <p>
        <strong>Equipamento:</strong>
        <%= @rental.product.description %>
      </p>

      <p>
        <strong>Período:</strong>
        <%= @rental.begin_date.strftime("%d/%m/%Y") %> a <%= @rental.end_date.strftime("%d/%m/%Y") %>
      </p>

      <p>
        <strong>Total:</strong>
        R$ <%= "%.2f" % (@rental.rental_price.to_f/100) %>
      </p>

      <p>
        <strong>Contato <%= current_user.id == @rental.user_id ? "proprietário" : "usuário" %>:</strong>
        <%= current_user.id == @rental.user_id ? User.find(@rental.product.user_id).email : User.find(@rental.user_id).email %>
      </p>
    </div>
    <div>
      <%= link_to 'Enviar Avaliação', review_path, class: "btn btn-ghost" %>
      <%= link_to 'Voltar', root_path, class: "btn btn-ghost" %>

    </div>
  </div>
</div>
<% if current_user.id == @rental.product.user_id  %>
    <div class="review-container mt-20">

        <table class="table table-borderless">
            <div class="title">Comentários</div>
            <thead>
            <% if @reviews.size.positive? %>
                <tr>
                <th scope="col">Produto</th>
                <th scope="col">Comentário</th>
                </tr>
            </thead>
            <tbody>
                <% @reviews.keys.each do |prod| %>
                <tr>
                <td><%= prod %></td>
                <td><%= @reviews[prod] %></td>
                </tr>
                <% end %>
                <% else %>
                <p class="title">Seja o primeiro a comentar</p>
                <% end %>
            </tbody>
        </table>
<% end %>

    </div>
<% else %>
    <p>Acesso não autorizado</p>
<%= link_to 'Voltar', root_path, class: "btn btn-ghost" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © 2020 SportsForRent, Inc. All rights reserved
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "bike.png", class: "logo", width: 300 %>
    <% end %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">SportsForRent
    </li>
  </ul>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">

          <%= link_to current_user.email, root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Incluir Equipamento", new_product_path, class: "dropdown-item" %>
            <%= link_to "Meus Equipamentos", products_user_path, class: "dropdown-item" %>
            <%= link_to "Listar aluguéis", rental_list_path, class: "dropdown-item" %>
            <%= link_to "Deslogar", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Abra sua conta", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>